// ============================================
// FC26 Cheatsheet — Game Data
// ============================================

const CONTROLS_MAP = {
  ps: [
    { label: 'Sprint', key: 'R2' },
    { label: 'Skill Move', key: 'R Stick' },
    { label: 'Pass', key: 'X' },
    { label: 'Through Ball', key: 'Triangle' },
    { label: 'Lob Pass', key: 'Square' },
    { label: 'Cross', key: 'Square' },
    { label: 'Shoot', key: 'Circle' },
    { label: 'Finesse Shot', key: 'R1 + Circle' },
    { label: 'Tackle', key: 'Circle' },
    { label: 'Jockey', key: 'L2' },
    { label: 'Contain', key: 'X' },
    { label: 'Switch Player', key: 'L1' },
    { label: 'Driven Pass', key: 'R1 + X' },
    { label: 'Chip Shot', key: 'L1 + Circle' },
    { label: 'Power Shot', key: 'L1 + R1 + Circle' },
    { label: 'Player Run', key: 'L1 + X' },
  ],
  xbox: [
    { label: 'Sprint', key: 'RT' },
    { label: 'Skill Move', key: 'R Stick' },
    { label: 'Pass', key: 'A' },
    { label: 'Through Ball', key: 'Y' },
    { label: 'Lob Pass', key: 'X' },
    { label: 'Cross', key: 'X' },
    { label: 'Shoot', key: 'B' },
    { label: 'Finesse Shot', key: 'RB + B' },
    { label: 'Tackle', key: 'B' },
    { label: 'Jockey', key: 'LT' },
    { label: 'Contain', key: 'A' },
    { label: 'Switch Player', key: 'LB' },
    { label: 'Driven Pass', key: 'RB + A' },
    { label: 'Chip Shot', key: 'LB + B' },
    { label: 'Power Shot', key: 'LB + RB + B' },
    { label: 'Player Run', key: 'LB + A' },
  ],
  pc: [
    { label: 'Sprint', key: 'Shift' },
    { label: 'Skill Move', key: 'Mouse Move' },
    { label: 'Pass', key: 'A / Space' },
    { label: 'Through Ball', key: 'W' },
    { label: 'Lob Pass', key: 'Q' },
    { label: 'Cross', key: 'Q' },
    { label: 'Shoot', key: 'D' },
    { label: 'Finesse Shot', key: 'E + D' },
    { label: 'Tackle', key: 'D' },
    { label: 'Jockey', key: 'S' },
    { label: 'Contain', key: 'A' },
    { label: 'Switch Player', key: 'E' },
    { label: 'Driven Pass', key: 'E + A' },
    { label: 'Chip Shot', key: 'E + D' },
    { label: 'Power Shot', key: 'E + Q + D' },
    { label: 'Player Run', key: 'E + Space' },
  ],
};

const SKILL_MOVES = [
  // 1 Star
  {
    name: 'Body Feint',
    stars: 1,
    difficulty: 'Easy',
    badge: 'badge-green',
    desc: 'A quick body sway to shift your opponent. Great for creating small openings in tight spaces.',
    ps: 'R Stick Left/Right',
    xbox: 'R Stick Left/Right',
    pc: 'Skill Stick Left/Right',
    tip: 'Best used when facing the defender head-on at walking pace.',
  },
  {
    name: 'Ball Juggle',
    stars: 1,
    difficulty: 'Easy',
    badge: 'badge-green',
    desc: 'Flick the ball up to begin juggling. Useful for setting up volleys and skill chains.',
    ps: 'L2 + R3 (click)',
    xbox: 'LT + R3 (click)',
    pc: 'S + Skill Click',
    tip: 'Tap shoot while juggling for a volley attempt.',
  },
  {
    name: 'Directional Nutmeg',
    stars: 1,
    difficulty: 'Easy',
    badge: 'badge-green',
    desc: 'Attempt to poke the ball through the defender\'s legs in a chosen direction.',
    ps: 'R1 + L Stick toward defender',
    xbox: 'RB + L Stick toward defender',
    pc: 'E + Move toward defender',
    tip: 'Only works when very close to a defender. High risk, high reward.',
  },

  // 2 Star
  {
    name: 'Feint & Exit',
    stars: 2,
    difficulty: 'Easy',
    badge: 'badge-green',
    desc: 'Fake one way and exit the other. Reliable and effective against rushing defenders.',
    ps: 'R Stick feint + exit direction',
    xbox: 'R Stick feint + exit direction',
    pc: 'Skill Stick feint + exit',
    tip: 'Works best at medium speed. Don\'t sprint into it.',
  },
  {
    name: 'Drag Back',
    stars: 2,
    difficulty: 'Easy',
    badge: 'badge-green',
    desc: 'Pull the ball back and change direction. One of the most useful moves in the game.',
    ps: 'R1 + L Stick back',
    xbox: 'RB + L Stick back',
    pc: 'E + Move back',
    tip: 'Perfect for creating space when your back is to goal.',
  },
  {
    name: 'Ball Roll',
    stars: 2,
    difficulty: 'Easy',
    badge: 'badge-green',
    desc: 'Roll the ball sideways with the sole of the foot. Simple but effective for beating lunging tacklers.',
    ps: 'R Stick Left/Right (hold)',
    xbox: 'R Stick Left/Right (hold)',
    pc: 'Skill Stick Left/Right (hold)',
    tip: 'Hold the stick to roll further. Combine with a quick pass.',
  },
  {
    name: 'Heel Flick',
    stars: 2,
    difficulty: 'Medium',
    badge: 'badge-yellow',
    desc: 'Flick the ball ahead with your heel to accelerate past a defender.',
    ps: 'R Stick Up then Down',
    xbox: 'R Stick Up then Down',
    pc: 'Skill Stick Up then Down',
    tip: 'Great for bursting past a defender who is jockeying.',
  },

  // 3 Star
  {
    name: 'Roulette / Spin',
    stars: 3,
    difficulty: 'Medium',
    badge: 'badge-yellow',
    desc: 'A 360-degree spin with the ball. Changes direction quickly and beats pressing defenders.',
    ps: 'R Stick: rotate quarter circle forward',
    xbox: 'R Stick: rotate quarter circle forward',
    pc: 'Skill Stick: quarter circle',
    tip: 'Don\'t use while sprinting — you\'ll lose the ball.',
  },
  {
    name: 'Heel-to-Heel Flick',
    stars: 3,
    difficulty: 'Medium',
    badge: 'badge-yellow',
    desc: 'Flick the ball forward with alternating heels for a burst of speed.',
    ps: 'R Stick Up then Down (while running)',
    xbox: 'R Stick Up then Down (while running)',
    pc: 'Skill Stick Up then Down (while running)',
    tip: 'Most effective at full sprint to blow past a defender.',
  },
  {
    name: 'Fake Shot',
    stars: 3,
    difficulty: 'Easy',
    badge: 'badge-green',
    desc: 'Wind up to shoot then cancel. Deceives defenders and goalkeepers consistently.',
    ps: 'Circle then X (quickly)',
    xbox: 'B then A (quickly)',
    pc: 'D then Space (quickly)',
    tip: 'The most versatile move. Works in almost every situation.',
  },
  {
    name: 'Fake Shot Stop',
    stars: 3,
    difficulty: 'Medium',
    badge: 'badge-yellow',
    desc: 'Perform a fake shot and stop dead. Perfect for wrong-footing opponents.',
    ps: 'Circle then X + release L Stick',
    xbox: 'B then A + release L Stick',
    pc: 'D then Space + stop moving',
    tip: 'Let go of all movement when you cancel to stop completely.',
  },
  {
    name: 'Step Over',
    stars: 3,
    difficulty: 'Medium',
    badge: 'badge-yellow',
    desc: 'Circle the ball with your foot without touching it. Classic dribbling move.',
    ps: 'R Stick: roll forward-right or forward-left',
    xbox: 'R Stick: roll forward-right or forward-left',
    pc: 'Skill Stick: roll forward to side',
    tip: 'Chain multiple step overs to keep the defender guessing.',
  },

  // 4 Star
  {
    name: 'Scoop Turn',
    stars: 4,
    difficulty: 'Medium',
    badge: 'badge-yellow',
    desc: 'Scoop the ball and turn in one motion. Great for quick 180-degree changes.',
    ps: 'Fake shot + L Stick left/right',
    xbox: 'Fake shot + L Stick left/right',
    pc: 'Fake shot + left/right',
    tip: 'Use in the box to create shooting angles from nothing.',
  },
  {
    name: 'Ball Roll Chop',
    stars: 4,
    difficulty: 'Medium',
    badge: 'badge-yellow',
    desc: 'Ball roll into a sharp chop cut. Fast direction change that beats aggressive defenders.',
    ps: 'R Stick hold side, then flick down',
    xbox: 'R Stick hold side, then flick down',
    pc: 'Skill Stick: hold side, flick down',
    tip: 'The chop comes out quickly — great for cutting inside from the wing.',
  },
  {
    name: 'Elastico',
    stars: 4,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'Push the ball one way then snap it back the other. A signature Ronaldinho move.',
    ps: 'R Stick: outside to inside in a quick flick',
    xbox: 'R Stick: outside to inside in a quick flick',
    pc: 'Skill Stick: outside to inside',
    tip: 'Works best at slow speed when the defender is close.',
  },
  {
    name: 'Spin Flick',
    stars: 4,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'A flashy spin with a flick exit. Great for carrying the ball past multiple players.',
    ps: 'R Stick: spin + flick in exit direction',
    xbox: 'R Stick: spin + flick in exit direction',
    pc: 'Skill Stick: spin + flick',
    tip: 'Requires good timing. Practice in the skill arena first.',
  },
  {
    name: 'Drag to Heel',
    stars: 4,
    difficulty: 'Medium',
    badge: 'badge-yellow',
    desc: 'Drag the ball back then flick it forward with the heel. Smooth and effective.',
    ps: 'L1 + R Stick back, then forward',
    xbox: 'LB + R Stick back, then forward',
    pc: 'Q + Skill Stick back, then forward',
    tip: 'Great when you need to create space near the edge of the box.',
  },
  {
    name: 'Three Touch Roulette',
    stars: 4,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'A slow, deliberate roulette with three touches. More controlled than the standard spin.',
    ps: 'Hold L2 + R Stick rotate',
    xbox: 'Hold LT + R Stick rotate',
    pc: 'Hold S + Skill Stick rotate',
    tip: 'Best used at walking pace. The slow tempo throws off rushing defenders.',
  },

  // 5 Star
  {
    name: 'Elastico Chop',
    stars: 5,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'An elastico followed by a sharp chop. One of the most effective 5-star moves for beating defenders.',
    ps: 'R Stick: flick outside to inside, then chop',
    xbox: 'R Stick: flick outside to inside, then chop',
    pc: 'Skill Stick: outside-inside then chop',
    tip: 'Best performed when jogging. Don\'t sprint or you\'ll lose control.',
  },
  {
    name: 'Rabona Fake',
    stars: 5,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'Fake a rabona cross or shot. Catches opponents off guard on the wing.',
    ps: 'L2 + Fake Shot (on weak foot side)',
    xbox: 'LT + Fake Shot (on weak foot side)',
    pc: 'S + Fake Shot (on weak foot side)',
    tip: 'Only triggers when the ball is on the weak foot side.',
  },
  {
    name: 'Hocus Pocus',
    stars: 5,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'An outrageous behind-the-legs flick. Pure style points with real effectiveness.',
    ps: 'R Stick: inside to outside to inside',
    xbox: 'R Stick: inside to outside to inside',
    pc: 'Skill Stick: inside-outside-inside',
    tip: 'Very flashy. Use in 1v1 situations for maximum humiliation.',
  },
  {
    name: 'Tornado Spin',
    stars: 5,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'Flick the ball up and spin around it. Can be chained into volleys and other tricks.',
    ps: 'Hold L1 + R Stick flick up, then direction',
    xbox: 'Hold LB + R Stick flick up, then direction',
    pc: 'Hold E + Skill Stick up, then direction',
    tip: 'Chain into a volley for highlight-reel goals.',
  },
  {
    name: 'Sombrero Flick',
    stars: 5,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'Flick the ball over a defender\'s head. One of the most disrespectful moves in the game.',
    ps: 'R Stick Up, Up, Down (while standing)',
    xbox: 'R Stick Up, Up, Down (while standing)',
    pc: 'Skill Stick Up, Up, Down (while standing)',
    tip: 'Requires perfect spacing. Too far and it won\'t register.',
  },
  {
    name: 'Waka Waka',
    stars: 5,
    difficulty: 'Hard',
    badge: 'badge-red',
    desc: 'A lateral shuffle with multiple touches. Creates a unique angle to beat tight markers.',
    ps: 'R Stick: flick right, down, left (or mirror)',
    xbox: 'R Stick: flick right, down, left (or mirror)',
    pc: 'Skill Stick: right, down, left',
    tip: 'Best used on the wing to cut inside past a fullback.',
  },
];

const PASSING = [
  {
    name: 'Ground Pass',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Standard pass along the ground to a teammate. The foundation of your build-up play.',
    ps: 'X',
    xbox: 'A',
    pc: 'Space',
    tip: 'Aim with the left stick. Power determines distance.',
  },
  {
    name: 'Through Ball',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Pass into space ahead of a teammate\'s run. Essential for breaking defensive lines.',
    ps: 'Triangle',
    xbox: 'Y',
    pc: 'W',
    tip: 'Time it as your teammate begins their run. Too early and it\'s intercepted.',
  },
  {
    name: 'Lobbed Through Ball',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'An aerial through ball over the defense. Perfect for exploiting high defensive lines.',
    ps: 'L1 + Triangle',
    xbox: 'LB + Y',
    pc: 'E + W',
    tip: 'Use when the opponent plays a high line. Pace on the attacker is crucial.',
  },
  {
    name: 'Lob / Cross',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Aerial ball to switch play or cross into the box from the wing.',
    ps: 'Square',
    xbox: 'X',
    pc: 'Q',
    tip: 'Double tap for a low driven cross. Triple tap for a ground cross.',
  },
  {
    name: 'Driven Pass',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'A fast, hard pass along the ground. Reaches teammates quicker but harder to control.',
    ps: 'R1 + X',
    xbox: 'RB + A',
    pc: 'E + Space',
    tip: 'Great for quick passing in the final third. The receiver needs good ball control.',
  },
  {
    name: 'Driven Lob / Whipped Cross',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'A fast, driven aerial ball with dip. Ideal for quick crosses into the box.',
    ps: 'R1 + Square',
    xbox: 'RB + X',
    pc: 'E + Q',
    tip: 'The whipped cross is deadly near the penalty area for headed goals.',
  },
  {
    name: 'Threaded Through Ball',
    badge: 'badge-purple',
    badgeText: 'Pro',
    desc: 'A precise through ball threaded between defenders with extra curl and accuracy.',
    ps: 'R1 + Triangle',
    xbox: 'RB + Y',
    pc: 'E + W',
    tip: 'Slower than a regular through ball but much more accurate.',
  },
  {
    name: 'Flair Pass',
    badge: 'badge-purple',
    badgeText: 'Pro',
    desc: 'Backheel, scorpion, or other flashy pass. Requires the Flair trait on the player.',
    ps: 'L2 + X',
    xbox: 'LT + A',
    pc: 'S + Space',
    tip: 'Only works with players who have the Flair trait. Unpredictable but stylish.',
  },
  {
    name: 'Trigger Run',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Send a teammate on a forward run. Not a pass itself, but essential for creating passing options.',
    ps: 'L1 (tap)',
    xbox: 'LB (tap)',
    pc: 'E (tap)',
    tip: 'Tap L1 before passing to trigger a run from the nearest player.',
  },
  {
    name: 'Precision Pass',
    badge: 'badge-purple',
    badgeText: 'Pro',
    desc: 'Ultra-precise pass with manual targeting. Full control over exactly where the ball goes.',
    ps: 'R1 + L1 + X',
    xbox: 'RB + LB + A',
    pc: 'E + Q + Space',
    tip: 'Requires careful aim. Best used for tricky angles where auto-aim would target the wrong player.',
  },
  {
    name: 'Fake Pass',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'Wind up for a pass then cancel it. Deceives nearby opponents.',
    ps: 'X then Circle (quickly)',
    xbox: 'A then B (quickly)',
    pc: 'Space then D (quickly)',
    tip: 'Similar to a fake shot. Great for wrong-footing pressing opponents.',
  },
  {
    name: 'One-Two Pass',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Pass and move — give the ball and get it back. The classic wall pass combination.',
    ps: 'L1 + X, then X to return',
    xbox: 'LB + A, then A to return',
    pc: 'E + Space, then Space to return',
    tip: 'One of the most effective ways to break down compact defenses.',
  },
];

const SHOOTING = [
  {
    name: 'Normal Shot',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Standard shot on goal. Power and accuracy depend on player stats and your aim.',
    ps: 'Circle',
    xbox: 'B',
    pc: 'D',
    tip: '2-3 bars of power is usually optimal. Green timed finishing for max accuracy.',
  },
  {
    name: 'Finesse Shot',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Curl the ball into the corner with the inside of the foot. Best from just outside the box.',
    ps: 'R1 + Circle',
    xbox: 'RB + B',
    pc: 'E + D',
    tip: 'Aim far post from the edge of the box. Deadly with high curve players.',
  },
  {
    name: 'Power Shot',
    badge: 'badge-red',
    badgeText: 'Powerful',
    desc: 'A devastating shot with extra power and a dramatic wind-up. Harder to save but slower to execute.',
    ps: 'L1 + R1 + Circle',
    xbox: 'LB + RB + B',
    pc: 'E + Q + D',
    tip: 'Needs space to wind up. Green timed finishing makes these almost unsaveable.',
  },
  {
    name: 'Chip Shot',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Loft the ball over an advancing goalkeeper. Satisfying when it works.',
    ps: 'L1 + Circle',
    xbox: 'LB + B',
    pc: 'Q + D',
    tip: 'Only use when the keeper is off their line. Too much power and it goes over.',
  },
  {
    name: 'Low Driven Shot',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'A hard, low shot along the ground. Tough for keepers to get down to.',
    ps: 'L1 + R1 + Circle (less power)',
    xbox: 'LB + RB + B (less power)',
    pc: 'E + Q + D (less power)',
    tip: 'Use 1-2 bars of power. Great for close-range finishes.',
  },
  {
    name: 'Timed Finishing',
    badge: 'badge-purple',
    badgeText: 'Pro',
    desc: 'Press shoot a second time just as the player strikes the ball for a precision boost.',
    ps: 'Circle, then Circle again on contact',
    xbox: 'B, then B again on contact',
    pc: 'D, then D again on contact',
    tip: 'Green = perfect, Yellow = slight boost, Red = terrible miss. Practice the timing.',
  },
  {
    name: 'Outside Foot Shot',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'Strike the ball with the outside of the foot for unexpected curl. Requires the trait.',
    ps: 'L2 + Circle',
    xbox: 'LT + B',
    pc: 'S + D',
    tip: 'Players need the Outside Foot Shot trait. The curl is hard for keepers to read.',
  },
  {
    name: 'Volley / Header',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Strike the ball out of the air. Positioning and timing are everything.',
    ps: 'Circle (when ball is in air)',
    xbox: 'B (when ball is in air)',
    pc: 'D (when ball is in air)',
    tip: 'Use less power on headers. For volleys, green timed finishing is key.',
  },
  {
    name: 'Fake Shot (to create space)',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Cancel a shot wind-up to fool the goalkeeper and defenders, then shoot for real.',
    ps: 'Circle then X, then Circle',
    xbox: 'B then A, then B',
    pc: 'D then Space, then D',
    tip: 'One of the best techniques for 1v1 situations with the keeper.',
  },
  {
    name: 'Bicycle Kick',
    badge: 'badge-red',
    badgeText: 'Powerful',
    desc: 'An acrobatic overhead kick. Spectacular but very inconsistent.',
    ps: 'Circle (with back to goal, ball in air)',
    xbox: 'B (with back to goal, ball in air)',
    pc: 'D (with back to goal, ball in air)',
    tip: 'Requires the Acrobatic trait for best results. Pure highlight reel material.',
  },
];

const DEFENDING = [
  {
    name: 'Standing Tackle',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Standard tackle attempt. The bread and butter of defending.',
    ps: 'Circle',
    xbox: 'B',
    pc: 'D',
    tip: 'Time it right to win the ball cleanly. Mistimed = foul.',
  },
  {
    name: 'Slide Tackle',
    badge: 'badge-red',
    badgeText: 'Risky',
    desc: 'Slide along the ground to win the ball. Covers more distance but high foul risk.',
    ps: 'Square',
    xbox: 'X',
    pc: 'Q',
    tip: 'Last resort only. A missed slide tackle leaves you on the ground.',
  },
  {
    name: 'Jockey',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Hold a defensive stance to stay in front of the attacker without committing.',
    ps: 'L2 (hold)',
    xbox: 'LT (hold)',
    pc: 'S (hold)',
    tip: 'The most important defensive technique. Contain, don\'t commit.',
  },
  {
    name: 'Sprint Jockey',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Jockey while sprinting to keep up with fast attackers while maintaining defensive shape.',
    ps: 'L2 + R2 (hold both)',
    xbox: 'LT + RT (hold both)',
    pc: 'S + Shift (hold both)',
    tip: 'Use to track speedy wingers. You move faster but are slightly less agile.',
  },
  {
    name: 'Contain / Second Man Press',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'AI teammate applies pressure while you control another defender to cut passing lanes.',
    ps: 'R1 (hold)',
    xbox: 'RB (hold)',
    pc: 'E (hold)',
    tip: 'Don\'t overuse — opponents will exploit the gaps. Best for doubling up on the wing.',
  },
  {
    name: 'Player Switch',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Switch to the nearest player to the ball. Master this to control your defense.',
    ps: 'L1',
    xbox: 'LB',
    pc: 'E',
    tip: 'Use right stick for manual switch to a specific player.',
  },
  {
    name: 'Hard Tackle',
    badge: 'badge-red',
    badgeText: 'Risky',
    desc: 'An aggressive tackle with more force. Higher chance of winning the ball but also of fouling.',
    ps: 'Hold Circle',
    xbox: 'Hold B',
    pc: 'Hold D',
    tip: 'Yellow card risk. Use only when the situation demands it.',
  },
  {
    name: 'Shoulder Barge',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'Use your body to push the attacker off the ball. Legal if done shoulder-to-shoulder.',
    ps: 'Circle (when alongside attacker)',
    xbox: 'B (when alongside attacker)',
    pc: 'D (when alongside attacker)',
    tip: 'Works best with strong defenders against smaller attackers.',
  },
  {
    name: 'Offside Trap',
    badge: 'badge-purple',
    badgeText: 'Pro',
    desc: 'Push your defensive line up to catch attackers offside. Risky but effective on through balls.',
    ps: 'D-Pad Up (double tap)',
    xbox: 'D-Pad Up (double tap)',
    pc: 'Up Arrow (double tap)',
    tip: 'Only use when you see the through ball coming. Mistiming = free goal.',
  },
];

const SET_PIECES = [
  {
    name: 'Free Kick — Power Shot',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'A powerful, straight free kick aimed at goal. Best from 20-25 yards.',
    ps: 'Circle (3-4 bars power) + aim',
    xbox: 'B (3-4 bars power) + aim',
    pc: 'D (3-4 bars power) + aim',
    tip: 'Aim just inside the post and add slight curve with the left stick.',
  },
  {
    name: 'Free Kick — Curl Shot',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Bend the ball around the wall and into the corner. The classic free kick technique.',
    ps: 'Circle + L Stick to curl direction',
    xbox: 'B + L Stick to curl direction',
    pc: 'D + direction to curl',
    tip: 'Use a player with high free kick accuracy and curve stats.',
  },
  {
    name: 'Free Kick — Driven',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'A knuckleball-style free kick that dips and swerves unpredictably.',
    ps: 'L1 + R1 + Circle',
    xbox: 'LB + RB + B',
    pc: 'E + Q + D',
    tip: 'Less consistent but when it works, the keeper has no chance.',
  },
  {
    name: 'Free Kick — Pass',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Pass the ball from a free kick instead of shooting. Set up a better angle.',
    ps: 'X (to pass) or Triangle (through ball)',
    xbox: 'A (to pass) or Y (through ball)',
    pc: 'Space (to pass) or W (through ball)',
    tip: 'Often more effective than shooting. Catch the defense off guard.',
  },
  {
    name: 'Corner Kick',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Deliver the ball into the box. Aim for tall players with good heading.',
    ps: 'Square + aim with L Stick',
    xbox: 'X + aim with L Stick',
    pc: 'Q + aim with direction',
    tip: 'Near post corners are effective. Also try short corners to confuse the defense.',
  },
  {
    name: 'Penalty Kick',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Aim with the left stick, power with shoot. Keep your nerve and pick a side.',
    ps: 'Circle + L Stick to aim',
    xbox: 'B + L Stick to aim',
    pc: 'D + direction to aim',
    tip: 'Don\'t aim too far to the side — you\'ll miss. 2 bars of power down the middle is reliable.',
  },
  {
    name: 'Penalty — Stutter Run',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'Slow your run-up to throw off the goalkeeper\'s timing.',
    ps: 'L2 during run-up',
    xbox: 'LT during run-up',
    pc: 'S during run-up',
    tip: 'Can cause the keeper to dive early. Don\'t overdo it or you\'ll trip.',
  },
  {
    name: 'Throw-In — Quick',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'Take a quick throw-in before the opponent can set up defensively.',
    ps: 'X (quickly after whistle)',
    xbox: 'A (quickly after whistle)',
    pc: 'Space (quickly after whistle)',
    tip: 'Catches opponents off guard. Works well deep in their half.',
  },
];

const GOALKEEPING = [
  {
    name: 'Move Goalkeeper',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Manually control the goalkeeper\'s position. Essential for cutting angles.',
    ps: 'R3 (click) + R Stick to move',
    xbox: 'R3 (click) + R Stick to move',
    pc: 'Skill Click + Skill Stick',
    tip: 'Use to close down 1v1 situations. Don\'t wander too far from the line.',
  },
  {
    name: 'Rush Goalkeeper Out',
    badge: 'badge-red',
    badgeText: 'Risky',
    desc: 'Send your keeper charging out to close down the attacker. High risk, high reward.',
    ps: 'Triangle (hold)',
    xbox: 'Y (hold)',
    pc: 'W (hold)',
    tip: 'Only rush when the attacker is through on goal. A mistimed rush = easy chip.',
  },
  {
    name: 'Goalkeeper Dive',
    badge: 'badge-blue',
    badgeText: 'Advanced',
    desc: 'Manually aim your goalkeeper\'s dive when the shot comes in.',
    ps: 'R Stick + direction when shot comes',
    xbox: 'R Stick + direction when shot comes',
    pc: 'Skill Stick + direction',
    tip: 'Requires excellent reaction time. Best left to AI in most situations.',
  },
  {
    name: 'Drop Kick',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'A long kick from the goalkeeper\'s hands. Good for quick counter-attacks.',
    ps: 'Circle (while holding ball)',
    xbox: 'B (while holding ball)',
    pc: 'D (while holding ball)',
    tip: 'Aim for a winger on the sideline to start a break.',
  },
  {
    name: 'Throw Ball',
    badge: 'badge-green',
    badgeText: 'Basic',
    desc: 'A precise throw to a nearby teammate. More accurate than a kick.',
    ps: 'X (while holding ball)',
    xbox: 'A (while holding ball)',
    pc: 'Space (while holding ball)',
    tip: 'Great for starting build-up play from the back.',
  },
  {
    name: 'Keeper Comes Out for Crosses',
    badge: 'badge-yellow',
    badgeText: 'Key',
    desc: 'Push the keeper to come claim crosses. Depends on the Comes for Crosses trait.',
    ps: 'Triangle (when cross comes in)',
    xbox: 'Y (when cross comes in)',
    pc: 'W (when cross comes in)',
    tip: 'High-rated keepers with the trait will punch or catch reliably.',
  },
];

const PRO_TIPS = [
  {
    icon: '&#127919;',
    iconClass: 'tip-icon-purple',
    title: 'Master the Fake Shot',
    text: 'The fake shot is the single most versatile move in the game. Use it to change direction, stop the ball dead, cut inside from the wing, or wrong-foot the keeper in a 1v1. It requires only 1-star skill moves and works in almost every situation.',
  },
  {
    icon: '&#128737;',
    iconClass: 'tip-icon-green',
    title: 'Defend with Jockey, Not Tackle',
    text: 'Resist the urge to tackle. Hold L2/LT to jockey and let the attacker run into you. Only press tackle when the ball is within reach. Patience beats aggression in FC26.',
  },
  {
    icon: '&#9889;',
    iconClass: 'tip-icon-yellow',
    title: 'Green Time Everything',
    text: 'Timed finishing applies to all shots. Hit the shoot button again just as your player\'s foot hits the ball. A green flash = perfect timing. It takes practice but massively improves shot accuracy.',
  },
  {
    icon: '&#128161;',
    iconClass: 'tip-icon-blue',
    title: 'Use L1/LB Trigger Runs',
    text: 'Tapping L1/LB before or during a pass sends the nearest teammate on a forward run. This is how you create passing options and overloads. Chain trigger runs with through balls to slice defenses open.',
  },
  {
    icon: '&#127939;',
    iconClass: 'tip-icon-red',
    title: 'Don\'t Always Sprint',
    text: 'Sprinting reduces your first touch and makes you easier to defend. Slow down when dribbling in tight spaces. Let go of sprint to execute skill moves cleanly and retain control.',
  },
  {
    icon: '&#128302;',
    iconClass: 'tip-icon-purple',
    title: 'Chain Skill Moves',
    text: 'The best dribblers combine moves. Try a ball roll into a fake shot, or a step over into a ball roll chop. Chaining keeps defenders guessing and creates more space than any single move.',
  },
  {
    icon: '&#9917;',
    iconClass: 'tip-icon-green',
    title: 'Driven Passes in the Final Third',
    text: 'Regular passes are too slow near the box. Use R1+X (RB+A) for driven passes that reach teammates faster and are harder to intercept. The receiving player needs decent ball control.',
  },
  {
    icon: '&#127942;',
    iconClass: 'tip-icon-yellow',
    title: 'Right Stick Player Switching',
    text: 'Don\'t rely on L1/LB for player switching — it often picks the wrong player. Flick the right stick toward the player you want to control for precise, manual switching.',
  },
  {
    icon: '&#128640;',
    iconClass: 'tip-icon-blue',
    title: 'Quick Counter Attack',
    text: 'When you win the ball, look for the quick long ball or through ball immediately. The opponent\'s defense is often out of position right after losing possession. Speed kills.',
  },
];
